### ISSUE TITLE
jvm: unhandled exception

### ISSUE THREAD

**Issue by ghost** [Raku/nqp#526] opened 2019-04-01 06:50 UTC
https://nurmi-labs.blogspot.com/2019/04/perl6.html

https://nurmi-labs.blogspot.com/2018/10/jdk.html

running BACKENDS=moar,jvm ./nqp.SlackBuild

Unhandled exception: java.lang.BootstrapMethodError: call site initialization exception

...

make: *** [gen/jvm/stage1/QAST.jar] Error 1

**Comment by usev6** [comment] 2023-02-06 20:37
I'm afraid we won't be able to find out what was wrong here -- or more to the point, if the problem is still relevant today. The links don't work any longer.

I'm closing the issue as "Won't fix"/"Can't repro".

**Closed by usev6** 2023-02-06 20:37 UTC
Labels: JVM
